#!/bin/sh

set -e

PREREQ=""

prereqs() {
  echo "$PREREQ"
}

case "$1" in
  prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

die() {
  echo "ERROR: $1" >&2
  exit 1
}

# Install certs
mkdir -p "$DESTDIR/etc/ssl/certs"
cp -a /etc/ssl/certs/ca-certificates.crt "$DESTDIR/etc/ssl/certs/" || die "/etc/ssl/certs/ca-certificates.crt not found"
cp -a /etc/ca-certificates.conf "$DESTDIR/etc/" || die "ca-certificates.conf not found"

exit 0
