version: 1
identity:
  hostname: idxe1
source:
  id: ubuntu-server-minimal
user-data:
  users:
    - name: idx
      passwd: "$6$U6V6cFmEGlYNjHMP$outUmvWxaDj2FaM92fCanrnqH/wxp968wNOUWfBYCUU/Ry89kh5atl4fxjnFbzr4eH/AZuzbo0iHsXRZ8r9Wm/"
ssh:
  install-server: true
  authorized-keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ2yM/uVAf4HQQ4xxs6nMuU3Fjkd9OOSUKOkqPLbuJt5 xps
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIBWL+1W3ds8rtQOXxkhFjvgEzPttRwecbhYruhgtcXJ m2
storage:
  layout:
    name: lvm
    password: "ChangeMe!"
packages:
  - vim-tiny
  - iputils-ping
